<?php

namespace NoteNest\Services;

use NoteNest\Models\Note;

class ExportService
{
    /**
     * Format a single note as GitHub-flavored Markdown
     */
    public static function formatNoteMarkdown(Note $note): string
    {
        $md = "# " . $note->title . "\n\n";
        $md .= "**Subject:** " . $note->subject . " | **Date:** " . $note->date . "\n\n";
        $md .= "> **Summary:** " . $note->summary . "\n\n";

        if (!empty($note->sections)) {
            foreach ($note->sections as $sec) {
                $heading = $sec['heading'] ?? 'Section';
                $type = $sec['type'] ?? 'theory';
                $content = $sec['content'] ?? '';
                $md .= "## " . $heading . " (" . $type . ")\n\n";
                $md .= $content . "\n\n";
            }
        } elseif (!empty($note->rawContent)) {
            $md .= $note->rawContent . "\n\n";
        } elseif (!empty($note->originalTranscript)) {
            $md .= "### Transcript\n\n" . $note->originalTranscript . "\n\n";
        }

        if (!empty($note->tags)) {
            $md .= "---\n**Tags:** " . implode(', ', $note->tags) . "\n";
        }

        return $md;
    }

    /**
     * Format all notes of a subject into a complete Markdown notebook
     */
    public static function formatRegisterMarkdown(string $subject, array $notes): string
    {
        $md = "# " . $subject . " Notebook\n\n";
        $md .= "*Generated by NoteNest AI on " . date('F j, Y') . "*\n\n";
        $md .= "---\n\n";

        foreach ($notes as $note) {
            $md .= self::formatNoteMarkdown($note);
            $md .= "\n\n---\n\n";
        }

        return $md;
    }

    /**
     * Generate printable HTML view for PDF generation or direct printing
     */
    public static function generatePrintableHtml(string $title, string $contentHtml): string
    {
        return <<<HTML
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{$title} - NoteNest</title>
    <style>
        @page { margin: 20mm; }
        body {
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
            color: #1e293b;
            line-height: 1.6;
            max-width: 800px;
            margin: 0 auto;
            padding: 20px;
        }
        h1 { font-size: 28px; color: #0f172a; margin-bottom: 8px; border-bottom: 2px solid #e2e8f0; padding-bottom: 8px; }
        h2 { font-size: 20px; color: #1e40af; margin-top: 24px; margin-bottom: 8px; }
        h3 { font-size: 16px; color: #475569; margin-top: 16px; }
        .meta { font-size: 13px; color: #64748b; margin-bottom: 16px; }
        .summary-box { background: #fefce8; border-left: 4px solid #facc15; padding: 12px 16px; margin: 16px 0; border-radius: 4px; font-style: italic; }
        .tag { display: inline-block; background: #f1f5f9; color: #475569; font-size: 12px; font-weight: bold; padding: 3px 8px; border-radius: 9999px; margin-right: 6px; }
        .type-badge { font-size: 11px; text-transform: uppercase; background: #e2e8f0; color: #334155; padding: 2px 6px; border-radius: 4px; vertical-align: middle; margin-left: 8px; }
        hr { border: none; border-top: 1px dashed #cbd5e1; margin: 24px 0; }
        @media print {
            body { padding: 0; }
            .no-print { display: none; }
        }
    </style>
</head>
<body>
    <div class="no-print" style="margin-bottom: 20px; text-align: right;">
        <button onclick="window.print()" style="background: #ea580c; color: white; border: none; padding: 8px 16px; border-radius: 6px; cursor: pointer; font-weight: bold;">
            Save / Print as PDF
        </button>
    </div>
    {$contentHtml}
</body>
</html>
HTML;
    }
}
