import { jsPDF } from 'jspdf';
import { Note } from '../types';

export const downloadFile = (filename: string, content: string | Blob, mimeType: string) => {
    const link = document.createElement('a');
    if (content instanceof Blob) {
        link.href = URL.createObjectURL(content);
    } else {
        link.href = `data:${mimeType};charset=utf-8,${encodeURIComponent(content)}`;
    }
    link.download = filename;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
};

const formatNoteMarkdown = (note: Note): string => {
    let md = `# ${note.title}\n\n`;
    md += `**Subject:** ${note.subject} | **Date:** ${note.date}\n\n`;
    md += `> **Summary:** ${note.summary}\n\n`;

    if (note.sections && note.sections.length > 0) {
        note.sections.forEach(sec => {
            md += `## ${sec.heading} (${sec.type})\n\n`;
            md += `${sec.content}\n\n`;
        });
    } else if (note.rawContent) {
        md += `${note.rawContent}\n\n`;
    } else if (note.originalTranscript) {
        md += `### Transcript\n\n${note.originalTranscript}\n\n`;
    }

    if (note.tags && note.tags.length > 0) {
        md += `\n---\n**Tags:** ${note.tags.join(', ')}\n`;
    }

    return md;
};

export const exportNoteAsMarkdown = (note: Note) => {
    const md = formatNoteMarkdown(note);
    downloadFile(`${note.title.replace(/[^a-z0-9]/gi, '_')}.md`, md, 'text/markdown');
};

export const exportRegisterAsMarkdown = (subject: string, notes: Note[]) => {
    let md = `# ${subject} Notebook\n\nGenerated by NoteNest\n\n---\n\n`;
    notes.forEach(note => {
        md += formatNoteMarkdown(note);
        md += `\n\n---\n\n`;
    });
    downloadFile(`${subject}_Notebook.md`, md, 'text/markdown');
};

const addNoteToPdf = (doc: jsPDF, note: Note, startY: number = 20): number => {
    const pageWidth = doc.internal.pageSize.getWidth();
    const margin = 20;
    const maxLineWidth = pageWidth - margin * 2;
    let y = startY;

    // Title
    doc.setFontSize(18);
    doc.setFont("helvetica", "bold");
    const titleLines = doc.splitTextToSize(note.title, maxLineWidth);
    doc.text(titleLines, margin, y);
    y += titleLines.length * 8;

    // Metadata
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(100);
    doc.text(`${note.subject} | ${note.date}`, margin, y);
    doc.setTextColor(0);
    y += 10;

    // Summary
    doc.setFontSize(11);
    doc.setFont("helvetica", "italic");
    const summaryLines = doc.splitTextToSize(`Summary: ${note.summary}`, maxLineWidth);
    doc.text(summaryLines, margin, y);
    y += summaryLines.length * 6 + 10;

    // Content
    doc.setFontSize(12);
    doc.setFont("helvetica", "normal");

    if (note.sections && note.sections.length > 0) {
        note.sections.forEach(sec => {
            if (y > doc.internal.pageSize.getHeight() - 20) {
                doc.addPage();
                y = 20;
            }

            doc.setFont("helvetica", "bold");
            doc.text(sec.heading, margin, y);
            y += 7;

            doc.setFont("helvetica", "normal");
            const contentLines = doc.splitTextToSize(sec.content, maxLineWidth);

            if (y + contentLines.length * 7 > doc.internal.pageSize.getHeight() - 20) {
                doc.addPage();
                y = 20;
            }

            doc.text(contentLines, margin, y);
            y += contentLines.length * 6 + 5;
        });
    } else if (note.rawContent) {
        const lines = doc.splitTextToSize(note.rawContent, maxLineWidth);
        if (y + lines.length * 7 > doc.internal.pageSize.getHeight() - 20) {
            doc.addPage();
            y = 20;
        }
        doc.text(lines, margin, y);
    }

    return y;
};

export const exportNoteAsPDF = (note: Note) => {
    const doc = new jsPDF();
    addNoteToPdf(doc, note);
    doc.save(`${note.title.replace(/[^a-z0-9]/gi, '_')}.pdf`);
};

export const exportRegisterAsPDF = (subject: string, notes: Note[]) => {
    const doc = new jsPDF();

    // Cover Page
    doc.setFontSize(24);
    doc.text(subject, 105, 100, { align: 'center' });
    doc.setFontSize(14);
    doc.text("NoteNest", 105, 110, { align: 'center' });
    doc.addPage();

    notes.forEach((note, index) => {
        addNoteToPdf(doc, note, 20);
        if (index < notes.length - 1) doc.addPage();
    });

    doc.save(`${subject}_Notebook.pdf`);
};